### ISSUE TITLE
SPARQL Query tab not initializing properly when loading some ontologies

### ISSUE THREAD

**Issue by samsontu** [protegeproject/protege#625]
Protege 5.2.0 (not present in Protege 5.1.0)

Steps to reproduce:
1. Start Protege 5.2.0
2. Add SPARQL Query tab
3. Load http://www.w3.org/ns/prov-o

The SPARQL Query tab is blank
Log: 
ERROR: 15:12:47 Uncaught Exception in thread 'AWT-EventQuery-0' (see log file for more details)
Log file:

...
2017-03-16 15:12:44.839 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of 'DL Query' tab
2017-03-16 15:12:44.840 [AWT-EventQueue-0] INFO  TabbedWorkspace    Disposed of workspace
2017-03-16 15:12:44.842 [AWT-EventQueue-0] INFO  OWLEditorKit    
2017-03-16 15:12:47.276 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoSuchMethodError: org.semanticweb.owlapi.rdf.model.AbstractTranslator.<init>(Lorg/semanticweb/owlapi/model/OWLOntologyManager;Lorg/semanticweb/owlapi/model/OWLOntology;ZLorg/semanticweb/owlapi/util/IndividualAppearance;)V
	at org.protege.owl.rdf.impl.RDFTranslator.<init>(RDFTranslator.java:91) ~[na:na]
	at org.protege.owl.rdf.impl.RDFTranslator.translate(RDFTranslator.java:53) ~[na:na]
	at org.protege.owl.rdf.impl.OwlTripleStoreImpl.addAxiom(OwlTripleStoreImpl.java:99) ~[na:na]
	at org.protege.owl.rdf.Utilities.loadOwlTripleStore(Utilities.java:48) ~[na:na]
	at org.protege.owl.rdf.Utilities.getOwlTripleStore(Utilities.java:32) ~[na:na]
	at org.protege.editor.owl.rdf.repository.BasicSparqlReasoner.precalculate(BasicSparqlReasoner.java:54) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView.initializeReasoner(SparqlQueryView.java:44) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView.initialiseOWLView(SparqlQueryView.java:34) ~[na:na]
	at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:43) ~[na:na]
	at org.protege.editor.core.ui.view.View.createContent(View.java:413) ~[na:na]
	at org.protege.editor.core.ui.view.View.createUI(View.java:220) ~[na:na]
	at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:124) ~[na:na]
	at java.awt.Component.processHierarchyEvent(Component.java:6692) ~[na:1.8.0_40]
	at java.awt.Component.processEvent(Component.java:6311) ~[na:1.8.0_40]
	at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.Component.createHierarchyEvents(Component.java:5541) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1443) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
	at java.awt.Component.show(Component.java:1622) ~[na:1.8.0_40]
	at java.awt.Component.show(Component.java:1654) ~[na:1.8.0_40]
	at java.awt.Component.setVisible(Component.java:1606) ~[na:1.8.0_40]
	at javax.swing.JComponent.setVisible(JComponent.java:2644) ~[na:1.8.0_40]
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394) ~[na:1.8.0_40]
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270) ~[na:1.8.0_40]
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132) ~[na:1.8.0_40]
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67) ~[na:1.8.0_40]
	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616) ~[na:1.8.0_40]
	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591) ~[na:1.8.0_40]
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647) ~[na:1.8.0_40]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) ~[na:1.8.0_40]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) ~[na:1.8.0_40]
	at java.awt.Component.processMouseEvent(Component.java:6522) ~[na:1.8.0_40]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_40]
	at java.awt.Component.processEvent(Component.java:6290) ~[na:1.8.0_40]
	at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2278) ~[na:1.8.0_40]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) ~[na:1.8.0_40]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:724) ~[na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) ~[na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]

**Comment by matthewhorridge** [comment]
Looks like this is due to some internal changes in the OWL API (this SPARQL tab relies on non-public constructors and classes).  It needs updating.

**Comment by csnyulas** [comment]
This has been fixed with new release of [rdf-library](https://github.com/protegeproject/rdf-library) and [sparql-query-plugin](https://github.com/protegeproject/sparql-query-plugin).

To get the fix update the the "OWLAPI RDF Library" and "Protege SPARQL Plugin" to the latest version with the auto-update mechanism (which appears when starting up Protege or can be activated through the `File -> Check for plugins...` menu):

![protege_update_sparql_plugin_to_v2 0 3](https://cloud.githubusercontent.com/assets/2441046/24934278/748e0c60-1ecf-11e7-9790-5fc38e7cbd74.png)

**Comment by ying6991** [comment]
![4](https://user-images.githubusercontent.com/26991546/35903724-61f13f02-0c1b-11e8-9a48-bcc95e164fde.png)

![3](https://user-images.githubusercontent.com/26991546/35903718-5ecac83e-0c1b-11e8-83a9-b030c772945a.jpg)

![2](https://user-images.githubusercontent.com/26991546/35903714-5b1c7606-0c1b-11e8-9e63-eaf4fb4d26c8.jpg)
@csnyulas 
After following the above steps, the SPARQL Query tab is still not working. But I copy all the files of Protégé 5.2 to other computers, it is able to show. Do you know how to solve? Thanks.
![1](https://user-images.githubusercontent.com/26991546/35903706-566fb91a-0c1b-11e8-88ef-8e4ec57c51cf.jpg)

The following screen shots are showing the versions of all the plugins installed and a SPARQL query tab.

**Comment by JatinLekkala** [comment]
I am not able to solve the above problem in my protege editor. Can anyone suggest other methods ?

**Comment by ali95123** [comment]
> I am not able to solve the above problem in my protege editor. Can anyone suggest other methods ?

Did you resolve your problem? I'm facing the same problem.

**Comment by samsontu** [comment]
Which version of Protege are you using and on which platform? The original problem reported in this issue had been resolved a long time ago. As far as I know, the SPARQL Query tab works in the current (5.6.2) version of Protege. (I am on a Mac.)
