### ISSUE TITLE
SPARQL Query tab Protégé 5.2

### ISSUE THREAD

**Issue by LiraNunezDavid** [protegeproject/protege#636]
I installed version 5.2 but the SPARQL Query tab does not work

**Comment by johardi** [comment]
Hi,
try to install the Snap SPARQL plugin instead. It is compatible with Protege 5.2

**Comment by csnyulas** [comment]
Seems like the same as #625 and protegeproject/sparql-query-plugin#10

**Comment by rsgoncalves** [comment]
@LiraNunezDavid could you post the error msg or stack trace that you're getting.

The plugin should be updated to use the same OWL API version as Protege in order to work.

**Comment by csnyulas** [comment]
BTW, for me this happens in v2.0.1 of the SPARQL Plug-in, which is bundled with Protege 5.2.

**Comment by rsgoncalves** [comment]
Fixed with new release of [rdf-library](https://github.com/protegeproject/rdf-library) and [sparql-query-plugin](https://github.com/protegeproject/sparql-query-plugin).

**Comment by csnyulas** [comment]
To fix the problem, update the the "OWLAPI RDF Library" and "Protege SPARQL Plugin" to the latest version with the auto-update mechanism (which appears when starting up Protege or can be activated through the `File -> Check for plugins...` menu):

![protege_update_sparql_plugin_to_v2 0 3](https://cloud.githubusercontent.com/assets/2441046/24934278/748e0c60-1ecf-11e7-9790-5fc38e7cbd74.png)

**Comment by LiraNunezDavid** [comment]
Thanks, after this update now the SPARQL Query tab started working again.

**Comment by ying6991** [comment]
After following the above steps, the SPARQL Query tab is still not working. But I copy all the files of Protégé 5.2 to other computers, it is able to show. Do you know how to solve?
The following screen shots are showing the versions of all the plugins installed and a SPARQL query tab. 
![1](https://user-images.githubusercontent.com/26991546/35903598-dabee3ea-0c1a-11e8-91f1-5cc34cae2cc6.jpg)
![2](https://user-images.githubusercontent.com/26991546/35903607-e24ae104-0c1a-11e8-8e39-d5261c1030b6.jpg)
![3](https://user-images.githubusercontent.com/26991546/35903614-e7806eb4-0c1a-11e8-806c-354fa9608f18.jpg)
![4](https://user-images.githubusercontent.com/26991546/35903617-ec8065ea-0c1a-11e8-8018-1391b102f5d7.png)
